"""Qualitative profile of each algorithm: what it needs, its pros and cons.

These are design-level facts (what components the method requires), not measurements.
The report combines them with measured cost and accuracy from the run records.

complexity_score = 1 + reference + reward_model + value_model + teacher + teacher_resident + 2 * online_generation
Each extra model held in memory or extra moving part adds a point; online generation adds two because it
needs a sampling engine and makes every step slower and harder to debug.
"""
from __future__ import annotations

from typing import Any

METHOD_PROFILES: dict[str, dict[str, Any]] = {
    "baseline": {
        "title": "Baseline (no training)",
        "signal": "none",
        "reference": False, "reward_model": False, "value_model": False,
        "teacher": False, "teacher_resident": False, "online_generation": False,
        "key_hparams": [],
        "pros": ["Anchors every comparison", "Costs only evaluation time"],
        "cons": ["Says nothing about what training adds"],
    },
    "sft": {
        "title": "Supervised fine-tuning",
        "signal": "demonstrations (prompt and target text)",
        "reference": False, "reward_model": False, "value_model": False,
        "teacher": False, "teacher_resident": False, "online_generation": False,
        "key_hparams": ["learning_rate", "epochs", "max_length", "lora_r"],
        "pros": ["Simplest and most stable", "Cheapest per step", "Strong baseline that later stages start from"],
        "cons": ["Only imitates, no signal about what is bad", "Quality capped by data quality", "Cannot optimise a verifiable or preference objective directly"],
    },
    "dpo": {
        "title": "Direct preference optimisation",
        "signal": "preference pairs (chosen, rejected)",
        "reference": True, "reward_model": False, "value_model": False,
        "teacher": False, "teacher_resident": False, "online_generation": False,
        "key_hparams": ["beta", "learning_rate", "epochs", "max_length"],
        "pros": ["No reward model and no sampling", "Supervised-style stability", "About two forward passes per pair; with LoRA the reference is the adapter switched off"],
        "cons": ["Needs a good preference dataset", "Off-policy, so it can drift from what the model actually generates", "Prone to length exploitation", "Sensitive to beta and learning rate"],
    },
    "rft": {
        "title": "Rejection-sampling fine-tuning",
        "signal": "verifier on the model's own samples",
        "reference": False, "reward_model": False, "value_model": False,
        "teacher": False, "teacher_resident": False, "online_generation": True,
        "key_hparams": ["samples_per_prompt", "temperature", "rounds", "learning_rate"],
        "pros": ["Simple, reuses the SFT trainer", "Robust, no RL instability"],
        "cons": ["Throws away failed samples", "Needs a verifiable task", "Sampling cost grows with n", "Diversity can collapse over rounds"],
    },
    "distill_seq": {
        "title": "Sequence-level distillation",
        "signal": "text generated by a teacher model",
        "reference": False, "reward_model": False, "value_model": False,
        "teacher": True, "teacher_resident": False, "online_generation": False,
        "key_hparams": ["teacher", "num_samples", "learning_rate"],
        "pros": ["Reuses SFT, training itself is cheap", "Teacher can be any model or API, no shared tokenizer needed"],
        "cons": ["Student only sees the teacher's samples, not its distribution", "One-off teacher generation cost", "Check the teacher's licence terms"],
    },
    "distill_kl": {
        "title": "Logit distillation (KL)",
        "signal": "teacher token distributions",
        "reference": False, "reward_model": False, "value_model": False,
        "teacher": True, "teacher_resident": True, "online_generation": False,
        "key_hparams": ["temperature", "kl_direction", "alpha", "learning_rate"],
        "pros": ["Richest signal per token, sample efficient", "No sampling loop"],
        "cons": ["Teacher must stay in memory during training", "Needs a shared tokenizer", "Memory heavy on a 16 GB card"],
    },
    "grpo": {
        "title": "Group relative policy optimisation",
        "signal": "reward function on sampled groups",
        "reference": True, "reward_model": False, "value_model": False,
        "teacher": False, "teacher_resident": False, "online_generation": True,
        "key_hparams": ["num_generations", "beta", "learning_rate", "max_completion_length", "temperature"],
        "pros": ["No value model, lighter than PPO", "Works with a rule-based reward, so no reward model", "Strong on reasoning tasks with checkable answers"],
        "cons": ["Generation dominates cost", "Needs a reliable verifiable reward", "No learning signal when every sample in a group scores the same", "Sensitive to group size and reward shaping"],
    },
    "ppo": {
        "title": "Proximal policy optimisation",
        "signal": "reward function or reward model, with a learned value baseline",
        "reference": True, "reward_model": False, "value_model": True,
        "teacher": False, "teacher_resident": False, "online_generation": True,
        "key_hparams": ["kl_coef", "clip_range", "gae_lambda", "vf_coef", "ppo_epochs", "minibatch_size", "learning_rate"],
        "pros": ["General: works with learned or rule-based rewards", "Token-level credit assignment through the value function"],
        "cons": ["Most memory: policy, reference and value head, plus generation", "Most hyperparameters and least stable", "Hard to debug, reward hacking risk"],
    },
}


def complexity_score(method: str) -> int:
    p = METHOD_PROFILES[method]
    return (
        1
        + int(p["reference"]) + int(p["reward_model"]) + int(p["value_model"])
        + int(p["teacher"]) + int(p["teacher_resident"])
        + 2 * int(p["online_generation"])
    )
